### ISSUE TITLE
Help with "Error in readJPEG(tmp): JPEG decompression error: Not a JPEG file"

### ISSUE THREAD

**Issue by jxwong** [dkahle/ggmap#107]
When I try to plot a map using the "get_map" function with the "stamen" "terrain-background" basemap, I get the error: Error in readJPEG(tmp) :  JPEG decompression error: Not a JPEG file: starts with 0x89 0x50. I tried other basemaps with no problems.

**Comment by dkahle** [comment]
This is fixed in the dev version. Please install that until it's on CRAN:
```r
devtools::install_github("dkahle/ggmap")
```
Thanks!

**Comment by jxwong** [comment]
Hi David,

I downloaded the dev version via devtools but I am still having the same
error.

Thanks,

Jo

**Comment by dkahle** [comment]
Minus some server problems, this works for me:
```{r}
library(ggmap)
map <- get_map(
  c(left = -95.80204, bottom = 29.38048, right = -94.92313, top = 30.14344),
  source = "stamen", maptype = "terrain-background"
)
ggmap(map)
```
I really think you're getting an older error. Can you link `devtools::session_info()` and give a reproducible example? Thanks!

**Comment by jxwong** [comment]
Hi David,

Sorry I just noticed that ggmap didn't load properly from github. I looked
around a bit for the solution but didn't find anything. I am not using the
dev version of ggplot2. The error I get is:

d> devtools::install_github("dkahle/ggmap")
Downloading GitHub repo dkahle/ggmap@master
from URL https://api.github.com/repos/dkahle/ggmap/zipball/master
Installing ggmap
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save
--no-restore --quiet CMD  \
  INSTALL
"C:/Users/User/AppData/Local/Temp/RtmpOS1TM8/devtools395c54bf1f4a/dkahle-ggmap-57b8572"
 \
  --library="C:/Users/User/Documents/R-dev" --install-tests

* installing *source* package 'ggmap' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
:
  there is no package called 'assertthat'
ERROR: lazy loading failed for package 'ggmap'
* removing 'C:/Users/User/Documents/R-dev/ggmap'
Error: Command failed (1)


Thanks!

**Comment by dkahle** [comment]
Looks like you need the __assertthat__ package:
```r
install.packages("assertthat")
```
