### ISSUE TITLE
Error when facet_wrap : Error in convertUnit(theme$strip.switch.pad.wrap, "cm") :  'x' argument must be a unit object

### ISSUE THREAD

**Issue by sillasgonzaga** [dkahle/ggmap#214]
Reproducible example:

```
> dput(example)
structure(list(LAT = c(-23.541451, -23.646386, -23.668478, -23.613932, 
-23.512421, -23.667435, -23.640681, -23.613113, -23.691493, -23.596402
), LON = c(-46.451615, -46.724327, -46.692946, -46.516565, -46.569992, 
-46.793313, -46.750106, -46.508092, -46.665821, -46.735918), 
    TEM_NOTURNO = c("N", "N", "N", "N", "N", "S", "S", "S", "S", 
    "S")), .Names = c("LAT", "LON", "TEM_NOTURNO"), row.names = c(NA, 
-10L), class = c("grouped_df", "tbl_df", "tbl", "data.frame"), vars = "TEM_NOTURNO", drop = TRUE, indices = list(
    0:4, 5:9), group_sizes = c(5L, 5L), biggest_group_size = 5L, labels = structure(list(
    TEM_NOTURNO = c("N", "S")), row.names = c(NA, -2L), class = "data.frame", vars = "TEM_NOTURNO", drop = TRUE, indices = list(
    0:4, 5:9), group_sizes = c(5L, 5L), biggest_group_size = 5L, labels = structure(list(
    TEM_NOTURNO = c("N", "S")), row.names = c(NA, -2L), class = "data.frame", vars = "TEM_NOTURNO", drop = TRUE, .Names = "TEM_NOTURNO"), .Names = "TEM_NOTURNO"))
> 
> qmplot(LON, LAT, data = example) + facet_wrap(~TEM_NOTURNO)
Using zoom = 11...
Error in convertUnit(theme$strip.switch.pad.wrap, "cm") : 
  'x' argument must be a unit object
```

However, using the same variable as color aesthetic works:

`qmplot(LON, LAT, data = example, color = TEM_NOTURNO)`

**Comment by sillasgonzaga** [comment]
Actually, I didn´t need to make a reproducibe example as the example described in the README no longer works.


```r
# define helper
`%notin%` <- function(lhs, rhs) !(lhs %in% rhs)


violent_crimes <- crime %>% 
  filter(
    offense %notin% c("auto theft", "theft", "burglary"),
    -95.39681 <= lon & lon <= -95.34188,
    29.73631 <= lat & lat <=  29.78400
  ) %>% 
  mutate(
    offense = fct_drop(offense),
    offense = fct_relevel(offense, 
                          c("robbery", "aggravated assault", "rape", "murder")
    )
  )
#> Error in crime %>% filter(offense %notin% c("auto theft", "theft", "burglary"), : could not find function "%>%"

qmplot(lon, lat, data = violent_crimes, maptype = "toner-background", color = offense) + 
  facet_wrap(~ offense)
#> Error in qmplot(lon, lat, data = violent_crimes, maptype = "toner-background", : could not find function "qmplot"
```

**Comment by scottmmjackson** [comment]
It looks like the example is missing the library requirement.

``` r
library(magrittr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(forcats)
library(ggmap)
#> Loading required package: ggplot2
#> Google Maps API Terms of Service: http://developers.google.com/maps/terms.
#> Please cite ggmap if you use it: see citation("ggmap") for details.
#> 
#> Attaching package: 'ggmap'
#> The following object is masked from 'package:magrittr':
#> 
#>     inset
# define helper
`%notin%` <- function(lhs, rhs) !(lhs %in% rhs)


violent_crimes <- crime %>% filter(offense %notin% c("auto theft", "theft", 
  "burglary"), -95.39681 <= lon & lon <= -95.34188, 29.73631 <= lat & lat <= 
  29.784) %>% mutate(offense = fct_drop(offense), offense = fct_relevel(offense, 
  c("robbery", "aggravated assault", "rape", "murder")))

qmplot(lon, lat, data = violent_crimes, maptype = "toner-background", color = offense) + 
  facet_wrap(~offense)
#> Using zoom = 14...
#> Source : http://tile.stamen.com/toner-background/14/3850/6770.png
#> Source : http://tile.stamen.com/toner-background/14/3851/6770.png
#> Source : http://tile.stamen.com/toner-background/14/3852/6770.png
#> Source : http://tile.stamen.com/toner-background/14/3853/6770.png
#> Source : http://tile.stamen.com/toner-background/14/3850/6771.png
#> Source : http://tile.stamen.com/toner-background/14/3851/6771.png
#> Source : http://tile.stamen.com/toner-background/14/3852/6771.png
#> Source : http://tile.stamen.com/toner-background/14/3853/6771.png
#> Source : http://tile.stamen.com/toner-background/14/3850/6772.png
#> Source : http://tile.stamen.com/toner-background/14/3851/6772.png
#> Source : http://tile.stamen.com/toner-background/14/3852/6772.png
#> Source : http://tile.stamen.com/toner-background/14/3853/6772.png
#> Source : http://tile.stamen.com/toner-background/14/3850/6773.png
#> Source : http://tile.stamen.com/toner-background/14/3851/6773.png
#> Source : http://tile.stamen.com/toner-background/14/3852/6773.png
#> Source : http://tile.stamen.com/toner-background/14/3853/6773.png
```

![](https://i.imgur.com/wCVngaQ.png)

**Comment by scottmmjackson** [comment]
Similarly I can't reproduce your top example. This run failed to grab tiles because I'm over the usage limit on stamen, but your error doesn't appear.

Install the `devtools` package using `install.packages("devtools")` and then execute `devtools::install_github('dkahle/ggmap')` and see if this fixes your problem. If so, please let me know so I can close this issue.

``` r
library(ggmap)
#> Loading required package: ggplot2
#> Google Maps API Terms of Service: http://developers.google.com/maps/terms.
#> Please cite ggmap if you use it: see citation("ggmap") for details.
example <- structure(list(LAT = c(-23.541451, -23.646386, -23.668478, -23.613932, 
  -23.512421, -23.667435, -23.640681, -23.613113, -23.691493, -23.596402), 
  LON = c(-46.451615, -46.724327, -46.692946, -46.516565, -46.569992, -46.793313, 
    -46.750106, -46.508092, -46.665821, -46.735918), TEM_NOTURNO = c("N", 
    "N", "N", "N", "N", "S", "S", "S", "S", "S")), .Names = c("LAT", "LON", 
  "TEM_NOTURNO"), row.names = c(NA, -10L), class = c("grouped_df", "tbl_df", 
  "tbl", "data.frame"), vars = "TEM_NOTURNO", drop = TRUE, indices = list(0:4, 
  5:9), group_sizes = c(5L, 5L), biggest_group_size = 5L, labels = structure(list(TEM_NOTURNO = c("N", 
  "S")), row.names = c(NA, -2L), class = "data.frame", vars = "TEM_NOTURNO", 
  drop = TRUE, indices = list(0:4, 5:9), group_sizes = c(5L, 5L), biggest_group_size = 5L, 
  labels = structure(list(TEM_NOTURNO = c("N", "S")), row.names = c(NA, -2L), 
    class = "data.frame", vars = "TEM_NOTURNO", drop = TRUE, .Names = "TEM_NOTURNO"), 
  .Names = "TEM_NOTURNO"))
qmplot(LAT, LON, data = example) + facet_wrap(~TEM_NOTURNO)
#> Using zoom = 12...
#> Source : http://tile.stamen.com/toner-lite/12/1778/2645.png
#> Source : http://tile.stamen.com/toner-lite/12/1779/2645.png
#> Source : http://tile.stamen.com/toner-lite/12/1780/2645.png
#> Source : http://tile.stamen.com/toner-lite/12/1778/2646.png
#> Source : http://tile.stamen.com/toner-lite/12/1779/2646.png
#> Source : http://tile.stamen.com/toner-lite/12/1780/2646.png
#> Source : http://tile.stamen.com/toner-lite/12/1778/2647.png
#> Source : http://tile.stamen.com/toner-lite/12/1779/2647.png
#> Source : http://tile.stamen.com/toner-lite/12/1780/2647.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1778/2648.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1779/2648.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1780/2648.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1778/2649.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1779/2649.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1780/2649.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1778/2650.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1779/2650.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1780/2650.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1778/2651.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1779/2651.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1780/2651.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1778/2652.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1779/2652.png
#> Source FAILED : http://tile.stamen.com/toner-lite/12/1780/2652.png
```

![](https://i.imgur.com/A0PbFwj.png)

**Comment by sillasgonzaga** [comment]
The error with the example from the documentation still occurs when I load all the packages required. I copied and pasted your code, including the ```library()``` calls, and it produces the same error for me.

Here´s my session info data:

```
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.3 (2017-11-30)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       America/Sao_Paulo           
#>  date     2018-04-24
#> Packages -----------------------------------------------------------------
#>  package   * version date       source                          
#>  backports   1.1.2   2017-12-13 CRAN (R 3.4.3)                  
#>  base      * 3.4.3   2017-12-06 local                           
#>  compiler    3.4.3   2017-12-06 local                           
#>  datasets  * 3.4.3   2017-12-06 local                           
#>  devtools    1.13.4  2017-11-09 CRAN (R 3.4.3)                  
#>  digest      0.6.15  2018-01-28 CRAN (R 3.4.3)                  
#>  evaluate    0.10.1  2017-06-24 CRAN (R 3.4.3)                  
#>  graphics  * 3.4.3   2017-12-06 local                           
#>  grDevices * 3.4.3   2017-12-06 local                           
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.4.3)                  
#>  knitr       1.19    2018-01-29 CRAN (R 3.4.3)                  
#>  magrittr    1.5     2014-11-22 CRAN (R 3.4.3)                  
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.4.3)                  
#>  methods   * 3.4.3   2017-12-06 local                           
#>  Rcpp        0.12.15 2018-01-20 CRAN (R 3.4.3)                  
#>  rmarkdown   1.9     2018-03-01 CRAN (R 3.4.4)                  
#>  rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.3)                  
#>  stats     * 3.4.3   2017-12-06 local                           
#>  stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)                  
#>  stringr     1.3.0   2018-02-19 CRAN (R 3.4.3)                  
#>  tools       3.4.3   2017-12-06 local                           
#>  utils     * 3.4.3   2017-12-06 local                           
#>  withr       2.1.2   2018-03-19 Github (jimhester/withr@79d7b0d)
#>  yaml        2.1.16  2017-12-12 CRAN (R 3.4.3)

```

**Comment by scottmmjackson** [comment]
Also, were you able to fix the error with your own block?

**Comment by dkahle** [comment]
Perhaps I merged prematurely? @scottmmjackson I'll let you check/close. Thanks!

**Comment by scottmmjackson** [comment]
I was never able to reproduce the issue, so @sillasgonzaga, if getting the latest from `devtools::install_github('dkahle/ggmap')` doesn't fix your problem, please comment in this issue.
