### ISSUE TITLE
Issue with installation in Mac

### ISSUE THREAD

**Issue by rajparmar46** [dkahle/ggmap#238]
#Error while installing the package

I'm working on an assignment and tried everything to make ggmap work on my mac but not able to install it. Somehow it ran in windows but throwing me below mentioned error.

Code:

```r
ggmap(get_googlemap())
}, si = TRUE)
```
Error in download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=29.763284,-95.363271&zoom=10&size=640x640&scale=2&maptype=terrain&sensor=false'
In addition: Warning message:
In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=29.763284,-95.363271&zoom=10&size=640x640&scale=2&maptype=terrain&sensor=false': HTTP status was '403 Forbidden'

Did this as well but don't know what exactly the error means.
```r
devtools::install_github("dkahle/ggmap", ref = "tidyup")
}, si = TRUE)
```
Downloading GitHub repo dkahle/ggmap@tidyup
tar: Failed to set default locale
tar: Failed to set default locale
   During startup - Warning messages:
   1: Setting LC_CTYPE failed, using "C" 
   2: Setting LC_TIME failed, using "C" 
   3: Setting LC_MESSAGES failed, using "C" 
   4: Setting LC_MONETARY failed, using "C" 
v  checking for file '/private/var/folders/jf/9tv5chwn5r11130x8_02xvcc0000gn/T/RtmpCIYm5L/remotes1edc61c07a23/dkahle-ggmap-4dfe516/DESCRIPTION' ...
-  preparing 'ggmap':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'ggmap/.github'
-  looking to see if a 'data/datalist' file should be added
-  building 'ggmap_2.7.904.tar.gz' (699ms)
   
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/jf/9tv5chwn5r11130x8_02xvcc0000gn/T//RtmpCIYm5L/file1edc6718ac74/ggmap_2.7.904.tar.gz' had non-zero exit status

**Comment by Linni93** [comment]
Update: I just downloaded the newest version of R (and RStudio) for Mac, and now it works for me :)

**Comment by dkahle** [comment]
Closing, if this continues to be a problem, please let me know and I'll reopen. (I think I addressed this on another thread.)

**Comment by csweths** [comment]
Yes, it is still a problem for me, on Mac get this error message.

> if (packageVersion("devtools") < 1.6) {
+   install.packages("devtools")
+ }
> devtools::install_github("bradleyboehmke/harrypotter")
Downloading GitHub repo bradleyboehmke/harrypotter@master
tar: Failed to set default locale
tar: Failed to set default locale
   During startup - Warning messages:
   1: Setting LC_CTYPE failed, using "C" 
   2: Setting LC_TIME failed, using "C" 
   3: Setting LC_MESSAGES failed, using "C" 
   4: Setting LC_MONETARY failed, using "C" 
v  checking for file '/private/var/folders/k1/srby67k12356gxq_w0zmxj380000gn/T/Rtmpz8BcFW/remotes2eb33707e9d/bradleyboehmke-harrypotter-51f7146/DESCRIPTION' ...
-  preparing 'harrypotter':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'harrypotter_0.1.0.tar.gz' (639ms)
   
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/k1/srby67k12356gxq_w0zmxj380000gn/T//Rtmpz8BcFW/file2eb3885fe56/harrypotter_0.1.0.tar.gz' had non-zero exit status

**Comment by dkahle** [comment]
Is this a __ggmap__ problem? It appears to only involve __devtools__ and __harrypotter__.

**Comment by csweths** [comment]
It is a devotes and harrypotter problem, but error message on Mac is similar, hence thought similar resolution can help solved this. 

Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error in i.p(...) :
(converted from warning) installation of package '/var/folders/k1/srby67k12356gxq_w0zmxj380000gn/T//Rtmpz8BcFW/file2eb3885fe56/harrypotter_0.1.0.tar.gz' had non-zero exit status

Thanks for helping out.
