### ISSUE TITLE
get_map error: file is not in PNG format

### ISSUE THREAD

**Issue by sco-lo-digital** [dkahle/ggmap#86]
Hi, this just started today. I had been using ggmap with no problem. I tried the ?get_map example code and it threw the same error. Did google make a change or something? looks like the get_map is getting a jpeg instead of a png and is throwing an error. Thanks for a great package and any help on the error.

**Comment by dkahle** [comment]
Did you get this working?  I'd just check/update ggmap...

**Comment by mic0331** [comment]
Hello, I'm running version 2.6.1 and have a similar issue, my code

> england = get_map(location = "england", zoom=7, maptype="road", source = "google")

and the error message 

> Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=england&zoom=7&size=640x640&scale=2&maptype=roadmap&language=en-EN&sensor=false
> Error in readPNG(tmp) : file is not in PNG format
> In addition: Warning message:
> In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
  download had nonzero exit status

**Comment by dkahle** [comment]
I think I fixed this a while back and forgot to close it, sorry! (And thanks for reporting!)

**Comment by bmcole** [comment]
This error is still persisting for me and several colleagues. Do you have any suggestions?

**Comment by ruthfortmann** [comment]
For me as well. I have been using the same line of code for the past two days with no problem at first. Today it starting throwing this error even though get_map seems to be downloading a png file in fact "Map from URL : http://tile.stamen.com/toner/6/43/25.png".
Any suggestions would be much appreciated!

**Comment by tungmilan** [comment]
Happened to me as well while trying knitting to HTML

```
Map from URL : http://tile.stamen.com/terrain/11/332/720.jpg
Quitting from lines 934-1004 (R_ggmap.Rmd) 
Error in readJPEG(tmp) : 
  JPEG decompression error: Not a JPEG file: starts with 0x89 0x50
Calls: <Anonymous> ... lapply -> FUN -> get_stamenmap_tile -> readJPEG -> .Call
```

Session Info

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] ggmap_2.6.1        ggplot2_2.2.1.9000
```

**Comment by dkahle** [comment]
Please try re-installing and comment back:
```r
if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap")
```

**Comment by tungmilan** [comment]
@dkahle : thank you. That fixed it

**Comment by dkahle** [comment]
Great!

**Comment by sarahgrogan** [comment]
@dkahle I'm also observing this error with the get_map function in v. 2.7.900, but was not seeing this previously (in v. 2.6?). 

```
> library(ggmap)
> map <- get_map(location = "texas", zoom = 6, source = "stamen")
Source : https://maps.googleapis.com/maps/api/staticmap?center=texas&zoom=6&size=640x640&scale=2&maptype=terrain
Error in readPNG(destfile) : file is not in PNG format
In addition: Warning message:
In download.file(url, destfile = destfile, quiet = !messaging, mode = "wb") :
  download had nonzero exit status
> packageVersion("ggmap")
[1] ‘2.7.900
```

Full session info:
```
> sessionInfo() R version 3.2.1 (2015-06-18) Platform: x86_64-unknown-linux-gnu (64-bit) Running under: Red Hat Enterprise Linux  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8        [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages:  [1] devtools_1.13.6      ggmap_2.7.900        maps_3.3.0           maptools_0.9-2       sp_1.3-1             lme4_1.1-18-1        Matrix_1.2-14        multcomp_1.4-8       TH.data_1.0-9        [10] MASS_7.3-50          survival_2.42-6      mvtnorm_1.0-8        agricolae_1.2-3      asremlPlus_2.0-12    Amelia_1.7.4         Rcpp_0.12.18         tidyr_0.8.1          myf_1.0              [19] plyr_1.8.4           BCS.PhenoData_1.3.78 BCS.Base_1.5.27      BCS.Generics_1.0.21  BCS.Data_1.0.26      asreml_3.0-1         lattice_0.20-35      dplyr_0.7.6          stringr_1.3.1        [28] openxlsx_3.0.0       doBy_4.6-2           ggplot2_3.0.0        prettydoc_0.2.1       loaded via a namespace (and not attached):  [1] nlme_3.1-128      bitops_1.0-6      gmodels_2.18.1    httr_1.3.1        rprojroot_1.2     tools_3.2.1       backports_1.0.5   R6_2.2.2          AlgDesign_1.1-7.3 lazyeval_0.2.1    colorspace_1.3-2  [12] withr_2.1.2       tidyselect_0.2.4  klaR_0.6-12       curl_3.2          git2r_0.23.0      sandwich_2.5-0    labeling_0.3      scales_1.0.0      digest_0.6.17     foreign_0.8-71    minqa_1.2.4       [23] rmarkdown_1.10    jpeg_0.1-8        pkgconfig_2.0.2   htmltools_0.3.6   rlang_0.2.2       rstudioapi_0.7    bindr_0.1.1       zoo_1.8-4         combinat_0.0-8    gtools_3.8.1      spdep_0.6-5       [34] magrittr_1.5      geosphere_1.5-5   munsell_0.5.0     proto_1.0.0       stringi_1.2.4     yaml_2.2.0        grid_3.2.1        gdata_2.18.0      crayon_1.3.4      deldir_0.1-15     splines_3.2.1     [45] mapproj_1.2.6     knitr_1.20        pillar_1.3.0      boot_1.3-20       rjson_0.2.20      reshape2_1.4.3    codetools_0.2-15  LearnBayes_2.15.1 glue_1.3.0        evaluate_0.10     png_0.1-7         [56] nloptr_1.0.4      RgoogleMaps_1.4.2 gtable_0.2.0      purrr_0.2.5       assertthat_0.2.0  coda_0.19-1       tibble_1.4.2      memoise_1.1.0     bindrcpp_0.2.2    cluster_2.0.7-1   dae_2.7-20
--



```

**Comment by dkahle** [comment]
@sarahgrogan I forgot to put in the correct `ref` in the `install_github(...)` call above. Run that, restart R, and try again.  Let me know if that doesn't work!

**Comment by sarahgrogan** [comment]
Thanks @dkahle, the edit above solved the problem, and I'm able to successfully create my map (after working around google's recent changes to access the api).

```
> map <- get_map(location = "texas", zoom = 6, source = "stamen")
Source : https://maps.googleapis.com/maps/api/staticmap?center=texas&zoom=6&size=640x640&scale=2&maptype=terrain
Error in get_googlemap(center = location, zoom = zoom, filename = filename) : 
  Forbidden (HTTP 403).

> map <- get_map(location = "texas", zoom = 6, source = "stamen")
Source : https://maps.googleapis.com/maps/api/staticmap?center=texas&zoom=6&size=640x640&scale=2&maptype=terrain
Error in geocode(center, source = "google") : 
  google now requires a (free) api key, see ?google_key.
```

**Comment by cperk** [comment]
I re-installed using the code above:

`if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup")`

And then restarted the R session but continue to get the 403 error.

**Comment by dkahle** [comment]
Please read this thread and check back: #51.

**Comment by cperk** [comment]
Thank you so much! Reading thread #51 helped a lot and get_map is working great now (once I set up a new project with Google Cloud, linked my payment info, and got the API key it was fixed).
